name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        versions: [6]
    env:
      repo: "govpf/hello" # Please don't forget to create the repo on Docker Hub
    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
#        context: ./${{ matrix.versions }}
        file: ./Dockerfile
#        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
